services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: