services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=test_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: